In [3]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

rawMovies = pd.read_csv("C:/Users/user/Downloads/Provided Code_TF-IDF/movies.csv")

vectorize = CountVectorizer()
bow = vectorize.fit_transform(rawMovies['genres'])
bow_df = pd.DataFrame(bow.toarray(),columns=vectorize.get_feature_names_out())
bow_df.set_index(rawMovies['title'],inplace=True)
print(bow_df.head(5).to_string())

                                    action  adventure  animation  children  comedy  crime  documentary  drama  fantasy  fi  film  genres  horror  imax  listed  musical  mystery  no  noir  romance  sci  thriller  war  western
title                                                                                                                                                                                                                           
Toy Story (1995)                         0          1          1         1       1      0            0      0        1   0     0       0       0     0       0        0        0   0     0        0    0         0    0        0
Jumanji (1995)                           0          1          0         1       0      0            0      0        1   0     0       0       0     0       0        0        0   0     0        0    0         0    0        0
Grumpier Old Men (1995)                  0          0          0         0       1      0           

In [4]:
totalKeywordsCnt = bow_df.sum(axis=1)
print(totalKeywordsCnt)

tf_df = bow_df.divide(totalKeywordsCnt, axis=0)
print(tf_df.head(5).to_string())

title
Toy Story (1995)                             5
Jumanji (1995)                               3
Grumpier Old Men (1995)                      2
Waiting to Exhale (1995)                     3
Father of the Bride Part II (1995)           1
                                            ..
Black Butler: Book of the Atlantic (2017)    4
No Game No Life: Zero (2017)                 3
Flint (2017)                                 1
Bungo Stray Dogs: Dead Apple (2018)          2
Andrew Dice Clay: Dice Rules (1991)          1
Length: 9742, dtype: int64
                                    action  adventure  animation  children    comedy  crime  documentary     drama   fantasy   fi  film  genres  horror  imax  listed  musical  mystery   no  noir   romance  sci  thriller  war  western
title                                                                                                                                                                                                                   

In [5]:
import  math
num_documents = len(bow_df)
idf_df = bow_df.apply(lambda col: math.log(num_documents / (sum(col) + 1)))
print(idf_df.head(5).to_string())

action       1.672677
adventure    2.042165
animation    2.767469
children     2.684415
comedy       0.952826


In [6]:
tf_idf_matrix = tf_df * idf_df
print(tf_idf_matrix.head(5).to_string())

                                    action  adventure  animation  children    comedy  crime  documentary     drama   fantasy   fi  film  genres  horror  imax  listed  musical  mystery   no  noir   romance  sci  thriller  war  western
title                                                                                                                                                                                                                                    
Toy Story (1995)                       0.0   0.408433   0.553494  0.536883  0.190565    0.0          0.0  0.000000  0.504982  0.0   0.0     0.0     0.0   0.0     0.0      0.0      0.0  0.0   0.0  0.000000  0.0       0.0  0.0      0.0
Jumanji (1995)                         0.0   0.680722   0.000000  0.894805  0.000000    0.0          0.0  0.000000  0.841636  0.0   0.0     0.0     0.0   0.0     0.0      0.0      0.0  0.0   0.0  0.000000  0.0       0.0  0.0      0.0
Grumpier Old Men (1995)                0.0   0.000000   0.000000

In [9]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
movieSimilarityMatrix = cosine_similarity(tf_idf_matrix)
print(movieSimilarityMatrix)

np.fill_diagonal(movieSimilarityMatrix,0)
print(movieSimilarityMatrix)

[[1.         0.82127694 0.08658008 ... 0.         0.46167621 0.18573055]
 [0.82127694 1.         0.         ... 0.         0.         0.        ]
 [0.08658008 0.         1.         ... 0.         0.         0.46615958]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.46167621 0.         0.         ... 0.         1.         0.        ]
 [0.18573055 0.         0.46615958 ... 0.         0.         1.        ]]
[[0.         0.82127694 0.08658008 ... 0.         0.46167621 0.18573055]
 [0.82127694 0.         0.         ... 0.         0.         0.        ]
 [0.08658008 0.         0.         ... 0.         0.         0.46615958]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.46167621 0.         0.         ... 0.         0.         0.        ]
 [0.18573055 0.         0.46615958 ... 0.         0.         0.        ]]
